---
- name: Deploy Docker Container on EC2
  hosts: azure_vms
  become: yes

  vars:
    container_name: frontend
    image_name:  navchakravarthy/frontend:latest


  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add User to Docker Group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Remove the container if exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Remove the old image if exists
      community.docker.docker_image:
        name: "{{ image_name }}"
        state: absent
        force_absent: true


    - name: Pull latest image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Start container with latest image
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"  # adjust ports as needed
